"""Tests for using past digests as context."""

import os
from datetime import datetime

from rss_digest import digest as digest_mod
from rss_digest.digest import (
    HISTORY_GUIDANCE,
    build_prompt,
    digest_date,
    digest_to_text,
    load_history,
    summarize,
    to_html,
)

TODAY = datetime.now().strftime("%Y-%m-%d")

# A date that is never "today", so fixtures with file-derived dates aren't skipped
# by the same-day exclusion.
NOT_TODAY = "1999-01-01"


def write(path, text, mtime=None):
    path.write_text(text)
    if mtime is not None:
        os.utime(path, (mtime, mtime))
    return path


# --- digest_to_text: markdown ---


def test_markdown_passes_through():
    assert digest_to_text("## Theme\n\nBody text.") == "## Theme\n\nBody text."


def test_markdown_strips_generated_header_and_footer():
    raw = (
        "# RSS Digest — 2026-08-18\n\n"
        "*148 articles · 57 sites*\n\n"
        "## Real Content\n\nKeep me.\n\n"
        "---\n*Generated by `anthropic/claude-sonnet-5`*\n"
    )
    out = digest_to_text(raw)
    assert "## Real Content" in out
    assert "Keep me." in out
    assert "RSS Digest" not in out
    assert "articles ·" not in out
    assert "Generated by" not in out


def test_strips_noise_regardless_of_emphasis_markers():
    # the stats line is wrapped in * in markdown and bare in converted HTML
    assert digest_to_text("*12 articles · 3 sites*") == ""
    assert digest_to_text("12 articles · 3 sites") == ""


def test_keeps_a_line_that_merely_mentions_articles():
    raw = "## Roundup\n\nThere were 12 articles worth reading this week."
    assert "12 articles worth reading" in digest_to_text(raw)


# --- digest_to_text: HTML ---


def test_html_links_become_markdown():
    raw = (
        '<html><body><p>See <a href="https://e.com/1">The Story</a>.</p></body></html>'
    )
    assert "[The Story](https://e.com/1)" in digest_to_text(raw)


def test_html_headings_become_markdown():
    raw = "<html><body><h2>Theme</h2><h3>Sub</h3></body></html>"
    out = digest_to_text(raw)
    assert "## Theme" in out
    assert "### Sub" in out


def test_html_list_items_become_bullets():
    raw = "<html><body><ul><li>one</li><li>two</li></ul></body></html>"
    out = digest_to_text(raw)
    assert "- one" in out
    assert "- two" in out


def test_html_style_block_is_dropped():
    raw = "<html><head><style>body { color: red; }</style></head><body><p>hi</p></body></html>"
    out = digest_to_text(raw)
    assert "color" not in out
    assert "hi" in out


def test_html_entities_are_unescaped():
    raw = (
        "<html><body><p>Tom &amp; Jerry &mdash; a &quot;classic&quot;</p></body></html>"
    )
    out = digest_to_text(raw)
    assert "Tom & Jerry" in out
    assert "&amp;" not in out


def test_html_fragment_without_body_still_converts():
    # not a full document, so the <html> sniff misses; must not crash
    assert "plain" in digest_to_text("plain text, no markup")


def test_round_trip_through_to_html():
    """The real pipeline: a digest written as HTML, read back on the next run."""
    body = "## A Theme\n\nRead [the story](https://e.com/1) and [another](https://e.com/2)."
    page = to_html(
        f"# RSS Digest — 2026-08-18\n\n*5 articles · 2 sites*\n\n{body}\n"
        f"\n---\n*Generated by `some/model`*",
        "RSS Digest — 2026-08-18",
    )
    out = digest_to_text(page)
    assert "## A Theme" in out
    assert "[the story](https://e.com/1)" in out
    assert "[another](https://e.com/2)" in out
    assert "RSS Digest" not in out
    assert "Generated by" not in out
    assert "articles ·" not in out
    assert "<" not in out  # no markup survived


# --- digest_date ---


def test_date_from_plain_filename(tmp_path):
    assert digest_date(write(tmp_path / "2026-08-17.html", "x")) == "2026-08-17"


def test_date_from_prefixed_filename(tmp_path):
    assert digest_date(write(tmp_path / "digest-2026-08-17.md", "x")) == "2026-08-17"


def test_date_from_anywhere_in_filename(tmp_path):
    assert (
        digest_date(write(tmp_path / "morning-2026-08-17-final.md", "x"))
        == "2026-08-17"
    )


def test_filename_date_wins_over_file_date(tmp_path):
    """An old date in the name must survive a file created today.

    This is the case that breaks if we date purely by creation time: moving a
    digest between volumes or restoring it from a sync service re-stamps the file.
    """
    p = write(tmp_path / "2020-01-02.md", "x")
    assert digest_date(p) == "2020-01-02"


def test_undated_filename_falls_back_to_file_date(tmp_path):
    # freshly written, so both st_birthtime (macOS) and st_mtime are today
    assert digest_date(write(tmp_path / "monday-reading.md", "x")) == TODAY


# --- load_history ---


def test_no_history_when_count_is_zero(tmp_path):
    write(tmp_path / "2026-08-17.md", "x")
    assert load_history(tmp_path, 0, TODAY) == []


def test_no_history_when_dir_missing(tmp_path):
    assert load_history(tmp_path / "nope", 3, TODAY) == []


def test_no_history_when_dir_empty(tmp_path):
    assert load_history(tmp_path, 3, TODAY) == []


def test_returns_newest_n_in_chronological_order(tmp_path):
    for d in ["2026-08-10", "2026-08-11", "2026-08-12", "2026-08-13"]:
        write(tmp_path / f"{d}.md", f"body {d}")
    assert [d for d, _ in load_history(tmp_path, 2, TODAY)] == [
        "2026-08-12",
        "2026-08-13",
    ]


def test_count_larger_than_archive_returns_all(tmp_path):
    write(tmp_path / "2026-08-10.md", "a")
    write(tmp_path / "2026-08-11.md", "b")
    assert len(load_history(tmp_path, 99, TODAY)) == 2


def test_todays_digest_is_excluded(tmp_path):
    write(tmp_path / f"{TODAY}.md", "today")
    write(tmp_path / "2026-08-10.md", "older")
    dates = [d for d, _ in load_history(tmp_path, 5, TODAY)]
    assert TODAY not in dates
    assert dates == ["2026-08-10"]


def test_arbitrary_filenames_are_accepted(tmp_path):
    write(tmp_path / "monday-reading.md", "monday")
    write(tmp_path / "weds.html", "<html><body><p>weds</p></body></html>")
    bodies = [t for _, t in load_history(tmp_path, 5, NOT_TODAY)]
    assert any("monday" in b for b in bodies)
    assert any("weds" in b for b in bodies)


def test_non_digest_files_are_ignored(tmp_path):
    write(tmp_path / "2026-08-10.md", "keep")
    write(tmp_path / "notes.txt", "ignore me")
    write(tmp_path / "data.json", "{}")
    (tmp_path / "subdir").mkdir()
    assert len(load_history(tmp_path, 5, TODAY)) == 1


def test_same_date_files_order_by_mtime(tmp_path):
    # undated names, so both resolve to the same (file) date; mtime breaks the tie
    write(tmp_path / "b.md", "second", mtime=2_000_000_200)
    write(tmp_path / "a.md", "first", mtime=2_000_000_100)
    bodies = [t for _, t in load_history(tmp_path, 5, NOT_TODAY)]
    assert bodies == ["first", "second"]


def test_history_content_is_converted(tmp_path):
    write(
        tmp_path / "2026-08-10.html",
        '<html><body><h2>T</h2><p><a href="https://e.com/1">Link</a></p></body></html>',
    )
    _, text = load_history(tmp_path, 1, TODAY)[0]
    assert "## T" in text
    assert "[Link](https://e.com/1)" in text


# --- build_prompt with history ---


ARTICLES = [
    {
        "feed_name": "Feed",
        "title": "Today Story",
        "url": "https://n.com/1",
        "summary": "s",
    },
]

HISTORY = [
    ("2026-08-16", "## Old Theme\n\nOld body."),
    ("2026-08-17", "## Newer\n\nNewer body."),
]


def test_prompt_without_history_is_unchanged():
    """No history must produce the exact prompt the tool sent before this feature."""
    assert build_prompt(ARTICLES, 24, []) == build_prompt(ARTICLES, 24)
    assert "previous_digests" not in build_prompt(ARTICLES, 24, [])


def test_prompt_wraps_history_in_a_tagged_block():
    prompt = build_prompt(ARTICLES, 24, HISTORY)
    assert "<previous_digests>" in prompt
    assert "</previous_digests>" in prompt


def test_prompt_labels_each_digest_with_its_date():
    prompt = build_prompt(ARTICLES, 24, HISTORY)
    assert "# Digest for 2026-08-16" in prompt
    assert "# Digest for 2026-08-17" in prompt


def test_prompt_keeps_history_before_todays_articles():
    prompt = build_prompt(ARTICLES, 24, HISTORY)
    assert prompt.index("</previous_digests>") < prompt.index("1 unread articles")


def test_prompt_still_contains_todays_articles():
    prompt = build_prompt(ARTICLES, 24, HISTORY)
    assert "[Today Story](https://n.com/1)" in prompt


# --- summarize: guidance is appended only when there is history ---


def capture(monkeypatch):
    """Stub litellm so we can inspect the messages that would be sent."""
    sent = {}

    class Msg:
        content = "digest body"

    class Choice:
        message = Msg()

    class Response:
        choices = [Choice()]

    def fake_completion(**kwargs):
        sent.update(kwargs)
        return Response()

    monkeypatch.setattr(digest_mod.litellm, "completion", fake_completion)
    return sent


def test_guidance_added_when_history_present(monkeypatch):
    sent = capture(monkeypatch)
    summarize(ARTICLES, 24, "m", "MY PROMPT", HISTORY)
    system = sent["messages"][0]["content"]
    assert system.startswith("MY PROMPT")
    assert HISTORY_GUIDANCE in system


def test_guidance_omitted_when_no_history(monkeypatch):
    sent = capture(monkeypatch)
    summarize(ARTICLES, 24, "m", "MY PROMPT", [])
    assert sent["messages"][0]["content"] == "MY PROMPT"


def test_custom_prompt_keeps_guidance(monkeypatch):
    """A --system-prompt-file replaces SYSTEM_PROMPT, but must not lose the
    history rules — otherwise custom prompts silently anchor on old digests."""
    sent = capture(monkeypatch)
    summarize(ARTICLES, 24, "m", "Totally custom prompt.", HISTORY)
    assert "Do NOT reuse their headings" in sent["messages"][0]["content"]


def test_history_reaches_the_user_message(monkeypatch):
    sent = capture(monkeypatch)
    summarize(ARTICLES, 24, "m", "P", HISTORY)
    assert "<previous_digests>" in sent["messages"][1]["content"]
